[package]
name = "sphere-n-rs"
version = "0.1.0"
edition = "2021"
description = "N-Sphere Code Generation in Rust"
repository = "https://github.com/luk036/sphere-n-rs"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.4"
lazy_static = "1.4.0"
interp = "1.0.2"
lds-rs = "0.1.1"
# lds-rs = { git = "https://github.com/luk036/lds-rs" }

[dev-dependencies]
approx_eq = "0.1.8"
